spring:
  profiles:
    active: local
  datasource:
    url: jdbc:h2:tcp://localhost/~/test2
    driver-class-name: org.h2.Driver
    username: sa
    password: "1234"
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: always

logging:
  level:
    root: INFO
    com:
      example:
        demo: INFO
    org.hibernate.SQL: debug